version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  json:
    format: '{"timestamp": "%(asctime)s", "service": "%(name)s", "level": "%(levelname)s", "message": "%(message)s"}'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: /var/log/pipexy/service.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

loggers:
  decoder:
    level: INFO
    handlers: [console, file]
    propagate: false

  encoder:
    level: INFO
    handlers: [console, file]
    propagate: false

  scaler:
    level: INFO
    handlers: [console, file]
    propagate: false

  motion:
    level: INFO
    handlers: [console, file]
    propagate: false

  object:
    level: INFO
    handlers: [console, file]
    propagate: false

  audio:
    level: INFO
    handlers: [console, file]
    propagate: false

root:
  level: INFO
  handlers: [console]
