global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'decoder'
    static_configs:
      - targets: ['decoder:5001']
    metrics_path: '/metrics'

  - job_name: 'encoder'
    static_configs:
      - targets: ['encoder:5002']
    metrics_path: '/metrics'

  - job_name: 'scaler'
    static_configs:
      - targets: ['scaler:5003']
    metrics_path: '/metrics'

  - job_name: 'motion'
    static_configs:
      - targets: ['motion:5004']
    metrics_path: '/metrics'

  - job_name: 'object'
    static_configs:
      - targets: ['object:5005']
    metrics_path: '/metrics'

  - job_name: 'audio'
    static_configs:
      - targets: ['audio:5006']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
